2024-09-25 09:22:22 - __main__ - INFO - Received data: update_id=304050829 message=Message(message_id=127, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727241742, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 09:22:22 - __main__ - INFO - Status: ok
2024-09-25 09:23:30 - __main__ - INFO - Received data: update_id=304050830 message=Message(message_id=128, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727241810, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 09:23:31 - __main__ - INFO - Status: ok
2024-09-25 09:23:58 - __main__ - INFO - Received data: update_id=304050831 message=Message(message_id=129, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727241838, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 09:23:58 - __main__ - INFO - Status: ok
2024-09-25 09:24:20 - __main__ - INFO - Received data: update_id=304050832 message=Message(message_id=130, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727241860, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 09:24:20 - __main__ - INFO - Status: ok
2024-09-25 09:25:36 - __main__ - INFO - Received data: update_id=304050833 message=Message(message_id=131, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727241937, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 09:25:36 - __main__ - INFO - Status: ok
2024-09-25 09:25:53 - __main__ - INFO - Received data: update_id=304050834 message=Message(message_id=132, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727241953, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 09:25:53 - __main__ - INFO - Status: ok
2024-09-25 09:26:02 - __main__ - INFO - Received data: update_id=304050835 message=Message(message_id=133, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727241962, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 09:26:02 - __main__ - INFO - Status: ok
2024-09-25 09:26:04 - __main__ - INFO - Received data: update_id=304050836 message=Message(message_id=134, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727241964, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 09:26:04 - __main__ - INFO - Status: ok
2024-09-25 09:26:12 - __main__ - INFO - Received data: update_id=304050837 message=Message(message_id=135, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727241972, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 09:26:12 - __main__ - INFO - Status: ok
2024-09-25 10:04:25 - __main__ - INFO - Received data: update_id=304050838 message=Message(message_id=136, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727244266, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:04:25 - __main__ - INFO - Status: ok
2024-09-25 10:04:31 - __main__ - INFO - Received data: update_id=304050839 message=Message(message_id=137, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727244271, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:04:31 - __main__ - INFO - Status: ok
2024-09-25 10:04:40 - __main__ - INFO - Received data: update_id=304050840 message=Message(message_id=138, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727244280, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:04:40 - __main__ - INFO - Status: ok
2024-09-25 10:19:27 - __main__ - INFO - Received data: update_id=304050841 message=Message(message_id=139, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245137, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:19:27 - __main__ - INFO - Status: ok
2024-09-25 10:19:27 - __main__ - INFO - Received data: update_id=304050842 message=Message(message_id=140, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245146, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:19:27 - __main__ - INFO - Status: ok
2024-09-25 10:19:29 - __main__ - INFO - Received data: update_id=304050843 message=Message(message_id=141, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245170, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:19:29 - __main__ - INFO - Status: ok
2024-09-25 10:22:51 - __main__ - INFO - Received data: update_id=304050844 message=Message(message_id=142, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245357, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:22:51 - __main__ - INFO - Status: ok
2024-09-25 10:22:51 - __main__ - INFO - Received data: update_id=304050845 message=Message(message_id=143, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245358, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:22:51 - __main__ - INFO - Status: ok
2024-09-25 10:22:51 - __main__ - INFO - Received data: update_id=304050846 message=Message(message_id=144, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245370, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:22:51 - __main__ - INFO - Status: ok
2024-09-25 10:22:56 - __main__ - INFO - Received data: update_id=304050847 message=Message(message_id=145, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245376, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:22:56 - __main__ - INFO - Status: ok
2024-09-25 10:22:58 - __main__ - INFO - Received data: update_id=304050848 message=Message(message_id=146, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245379, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:22:58 - __main__ - INFO - Status: ok
2024-09-25 10:24:19 - __main__ - INFO - Received data: update_id=304050849 message=Message(message_id=147, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245460, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:24:19 - __main__ - INFO - Status: ok
2024-09-25 10:27:27 - __main__ - INFO - Received data: update_id=304050850 message=Message(message_id=148, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245648, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:27:27 - __main__ - INFO - Status: ok
2024-09-25 10:28:05 - __main__ - INFO - Received data: update_id=304050851 message=Message(message_id=149, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245686, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:28:05 - __main__ - INFO - Status: ok
2024-09-25 10:28:28 - __main__ - INFO - Received data: update_id=304050852 message=Message(message_id=150, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245709, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:28:28 - __main__ - INFO - Status: ok
2024-09-25 10:28:35 - __main__ - INFO - Received data: update_id=304050853 message=Message(message_id=151, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727245715, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-25 10:28:35 - __main__ - INFO - Status: ok
2024-09-26 08:05:18 - __main__ - INFO - Received data: update_id=304050854 message=Message(message_id=152, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727323518, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:05:18 - __main__ - INFO - Status: ok
2024-09-26 08:05:26 - __main__ - INFO - Received data: update_id=304050855 message=Message(message_id=153, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727323527, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:05:26 - __main__ - INFO - Status: ok
2024-09-26 08:08:37 - __main__ - INFO - Received data: update_id=304050856 message=Message(message_id=154, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727323717, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:08:37 - __main__ - INFO - Status: ok
2024-09-26 08:08:38 - __main__ - INFO - Received data: update_id=304050857 message=Message(message_id=155, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727323719, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:08:38 - __main__ - INFO - Status: ok
2024-09-26 08:11:15 - __main__ - INFO - Received data: update_id=304050858 message=Message(message_id=156, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727323875, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:11:16 - __main__ - INFO - Status: ok
2024-09-26 08:11:21 - __main__ - INFO - Received data: update_id=304050859 message=Message(message_id=158, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727323881, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:11:21 - __main__ - INFO - Status: ok
2024-09-26 08:12:43 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000015AB9E2C690>
2024-09-26 08:13:18 - __main__ - INFO - Received data: update_id=304050860 message=Message(message_id=159, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727323998, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:13:18 - __main__ - INFO - Status: ok
2024-09-26 08:14:14 - __main__ - INFO - Received data: update_id=304050861 message=Message(message_id=160, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727324055, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:14:14 - __main__ - INFO - Status: ok
2024-09-26 08:16:12 - __main__ - INFO - Received data: update_id=304050862 message=Message(message_id=161, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727324172, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:16:12 - __main__ - INFO - Status: ok
2024-09-26 08:18:15 - __main__ - INFO - Received data: update_id=304050863 message=Message(message_id=162, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727324295, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:18:15 - __main__ - INFO - Status: ok
2024-09-26 08:22:44 - __main__ - INFO - Received data: update_id=304050864 message=Message(message_id=163, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727324565, text='/start', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:22:45 - __main__ - INFO - Status: ok
2024-09-26 08:22:48 - __main__ - INFO - Received data: update_id=304050865 message=Message(message_id=165, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727324569, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:22:48 - __main__ - INFO - Status: ok
2024-09-26 08:23:42 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002357912CA10>
2024-09-26 08:24:28 - __main__ - INFO - Received data: update_id=304050866 message=Message(message_id=166, from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727324668, text='/specialities_list', callback_query=None, location=None, successful_payment=None) callback_query=None pre_checkout_query=None
2024-09-26 08:24:28 - __main__ - INFO - Status: ok
2024-09-26 08:24:42 - __main__ - INFO - Received data: update_id=304050867 message=None callback_query=CallbackQuery(id='2567735149910350103', from_user=User(id=597847427, is_bot=False, first_name='Павел', username='kirsanov69', language_code='en'), message=Message(message_id=168, from_user=User(id=6451700525, is_bot=True, first_name='hotels_bot', username='Serch_hotels_api_bot', language_code=None), chat=Chat(id=597847427, type='private', username='kirsanov69', first_name='Павел', last_name=None), date=1727324669, text='Список менторов', callback_query=None, location=None, successful_payment=None), chat_instance='885813474494805680', data='speciality: Frontend', game_short_name=None) pre_checkout_query=None
2024-09-26 08:24:42 - __main__ - INFO - Status: ok
2024-09-26 08:26:13 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000029D10C2CB90>
2024-09-27 22:15:32 - __main__ - ERROR - Error in webhook handler: 'Update' object has no attribute 'bot'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 41, in webhook_handler
    await dp.feed_update(bot, update)
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 147, in feed_update
    if update.bot != bot:
       ^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Update' object has no attribute 'bot'
2024-09-27 22:17:05 - __main__ - ERROR - Error in webhook handler: 'str' object has no attribute 'message'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 14, in callback_handler
    message = callback.message
              ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'message'
2024-09-27 22:18:49 - __main__ - ERROR - Error in webhook handler: 'str' object has no attribute 'message'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 14, in callback_handler
    message = callback.message
              ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'message'
2024-09-27 22:20:06 - __main__ - ERROR - Error in webhook handler: 'str' object has no attribute 'text'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 14, in callback_handler
    message = message.text
              ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'text'
2024-09-27 22:22:09 - __main__ - ERROR - Error in webhook handler: 'str' object has no attribute 'text'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 15, in callback_handler
    response = get_ai_text(message.text)
                           ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'text'
2024-09-27 22:22:42 - __main__ - ERROR - Error in webhook handler: 'module' object is not callable
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 12, in get_ai_text
    client = openai(api_key=OPENAI_API_KEY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
2024-09-27 22:24:09 - __main__ - ERROR - Error in webhook handler: 'module' object is not callable
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 15, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 12, in get_ai_text
    client = openai(api_key=OPENAI_API_KEY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
2024-09-27 22:32:26 - __main__ - ERROR - Error in webhook handler: module 'openai' has no attribute 'OpenAI'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 15, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 11, in get_ai_text
    client = openai.OpenAI(api_key=OPENAI_API_KEY)
             ^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'OpenAI'
2024-09-27 22:36:56 - __main__ - ERROR - Error in webhook handler: beta
Traceback (most recent call last):
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\openai_object.py", line 59, in __getattr__
    return self[k]
           ~~~~^^^
KeyError: 'beta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 15, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 14, in get_ai_text
    thread = client.beta.threads.create()
             ^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\openai_object.py", line 61, in __getattr__
    raise AttributeError(*err.args)
AttributeError: beta
2024-09-27 22:58:47 - __main__ - ERROR - Error in webhook handler: 'OpenAI' object has no attribute 'id'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 19, in get_ai_text
    thread_id=thread.id,
              ^^^^^^^^^
AttributeError: 'OpenAI' object has no attribute 'id'
2024-09-27 23:01:24 - __main__ - ERROR - Error in webhook handler: Error code: 404 - {'error': {'message': "No thread found with id '<openai.OpenAI object at 0x0000012EA15DE110>'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 18, in get_ai_text
    message = client.beta.threads.messages.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\messages.py", line 99, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 947, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1051, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': "No thread found with id '<openai.OpenAI object at 0x0000012EA15DE110>'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-09-27 23:07:38 - __main__ - ERROR - Error in webhook handler: Error code: 404 - {'error': {'message': "No thread found with id 'thread_abc123'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 18, in get_ai_text
    message = client.beta.threads.messages.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\messages.py", line 99, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 947, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1051, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': "No thread found with id 'thread_abc123'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-09-27 23:13:49 - __main__ - ERROR - Error in webhook handler: Error code: 404 - {'error': {'message': "No thread found with id 'thread_abc123'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 18, in get_ai_text
    message = client.beta.threads.messages.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\messages.py", line 99, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 947, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1051, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': "No thread found with id 'thread_abc123'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-09-27 23:15:41 - __main__ - ERROR - Error in webhook handler: Error code: 404 - {'error': {'message': "No thread found with id 'thread_abc123'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 18, in get_ai_text
    message = client.beta.threads.messages.create(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\messages.py", line 99, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 947, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1051, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': "No thread found with id 'thread_abc123'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-09-27 23:16:46 - __main__ - ERROR - Error in webhook handler: 'OpenAI' object has no attribute 'id'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 20, in get_ai_text
    thread_id=thread.id,
              ^^^^^^^^^
AttributeError: 'OpenAI' object has no attribute 'id'
2024-09-27 23:24:04 - __main__ - ERROR - Error in webhook handler: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 36, in get_ai_text
    data = json.loads(result_text)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-27 23:25:17 - __main__ - ERROR - Error in webhook handler: Object of type Thread is not JSON serializable
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 24, in get_ai_text
    print(json.dumps(thread, indent=2))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Thread is not JSON serializable
2024-09-27 23:26:52 - __main__ - ERROR - Error in webhook handler: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 37, in get_ai_text
    data = json.loads(result_text)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-27 23:28:57 - __main__ - ERROR - Error in webhook handler: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    response = get_ai_text(message)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 38, in get_ai_text
    data = json.loads(result_text)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-27 23:30:32 - __main__ - ERROR - Error in webhook handler: 'str' object has no attribute 'chat'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 17, in callback_handler
    await bot.send_message(chat_id=message.chat.id, text=response)
                                   ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'chat'
2024-09-27 23:33:19 - __main__ - ERROR - Error in webhook handler: 'str' object has no attribute 'chat'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    await bot.send_message(chat_id=message.chat.id, text=response)
                                   ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'chat'
2024-09-27 23:36:15 - __main__ - ERROR - Error in webhook handler: 'str' object has no attribute 'chat'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    await bot.send_message(chat_id=message.chat.id, text=response)
                                   ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'chat'
2024-09-27 23:38:41 - __main__ - ERROR - Error in webhook handler: 'str' object has no attribute 'chat'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    await bot.send_message(chat_id=message.chat.id, text=response)
                                   ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'chat'
2024-09-27 23:43:49 - __main__ - ERROR - Error in webhook handler: 'str' object has no attribute 'chat'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    await bot.send_message(chat_id=message.chat.id, text=response)
                                   ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'chat'
2024-09-28 08:13:37 - __main__ - ERROR - Error in webhook handler: chat
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(text)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    await bot.send_message(chat_id=Message.chat.id, text=response)
                                   ^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 215, in __getattr__
    raise AttributeError(item)
AttributeError: chat
2024-09-28 08:17:21 - __main__ - ERROR - Error in webhook handler: 'Update' object has no attribute 'bot'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 41, in webhook_handler
    await dp.feed_update(bot, update)
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 147, in feed_update
    if update.bot != bot:
       ^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Update' object has no attribute 'bot'
2024-09-28 08:19:56 - __main__ - ERROR - Error in webhook handler: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    await bot.send_message(chat_id=message.chat.id, text=response)
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\aiogram\client\bot.py", line 2808, in send_message
    call = SendMessage(
           ^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
2024-09-28 08:21:35 - __main__ - INFO - Status: ok
2024-09-28 08:21:53 - __main__ - INFO - Status: ok
2024-09-28 08:27:02 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002F2C3BBE410>
2024-09-28 08:27:56 - __main__ - INFO - Status: ok
2024-09-28 08:29:31 - __main__ - INFO - Status: ok
2024-09-28 08:29:59 - __main__ - INFO - Status: ok
2024-09-28 08:32:05 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024C654BFBD0>
2024-09-28 08:32:36 - __main__ - INFO - Status: ok
2024-09-28 08:34:26 - __main__ - INFO - Status: ok
2024-09-28 08:34:54 - __main__ - INFO - Status: ok
2024-09-28 08:37:32 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020A259AAA10>
2024-09-28 08:40:51 - __main__ - INFO - Status: ok
2024-09-28 08:42:23 - __main__ - INFO - Status: ok
2024-09-28 08:44:37 - __main__ - INFO - Status: ok
2024-09-28 08:45:47 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000028401E55850>
2024-09-28 08:46:15 - __main__ - INFO - Status: ok
2024-09-28 08:46:47 - __main__ - INFO - Status: ok
2024-09-28 08:47:37 - __main__ - INFO - Status: ok
2024-09-28 08:49:22 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001959C99BF10>
2024-09-28 08:49:48 - __main__ - INFO - Status: ok
2024-09-28 08:50:21 - __main__ - INFO - Status: ok
2024-09-28 08:50:54 - __main__ - INFO - Status: ok
2024-09-28 08:51:22 - __main__ - INFO - Status: ok
2024-09-28 08:53:35 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000018D816B38D0>
2024-09-28 08:54:08 - __main__ - INFO - Status: ok
2024-09-28 09:13:57 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002A6F9123110>
2024-09-28 09:23:14 - __main__ - INFO - Status: ok
2024-09-28 09:23:33 - __main__ - INFO - Status: ok
2024-09-28 09:23:56 - __main__ - INFO - Status: ok
2024-09-28 09:25:50 - __main__ - INFO - Status: ok
2024-09-28 09:26:01 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002265234B9D0>
2024-09-28 09:26:01 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000226534FCE50>, 48858.375)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000226527F03D0>
2024-09-28 09:26:24 - __main__ - INFO - Status: ok
2024-09-28 09:26:46 - __main__ - INFO - Status: ok
2024-09-28 09:48:19 - __main__ - INFO - Status: ok
2024-09-28 10:18:13 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021AD9AAA490>
2024-09-28 10:22:48 - __main__ - INFO - Status: ok
2024-09-28 10:23:01 - __main__ - INFO - Status: ok
2024-09-28 10:23:13 - __main__ - INFO - Status: ok
2024-09-28 10:23:26 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000252B80F7F90>
2024-09-28 10:23:26 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000252B89FC520>, 52300.781)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000252B7A50150>
2024-09-28 10:23:49 - __main__ - INFO - Status: ok
2024-09-28 10:25:02 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000181091927D0>
2024-09-28 10:25:28 - __main__ - INFO - Status: ok
2024-09-28 10:25:42 - __main__ - INFO - Status: ok
2024-09-28 10:39:26 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000012F123A6A50>
2024-09-28 10:40:19 - __main__ - INFO - Status: ok
2024-09-28 10:40:44 - __main__ - INFO - Status: ok
2024-09-28 10:41:49 - __main__ - ERROR - Error in webhook handler: Error code: 404 - {'error': {'message': "No assistant found with id 'asst_sJetDGPplUfiq0x03Ba8Xvzq'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    response = get_ai_text(message.text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 21, in get_ai_text
    run = client.beta.threads.runs.create_and_poll(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\runs\runs.py", line 788, in create_and_poll
    run = self.create(
          ^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\runs\runs.py", line 535, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 947, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1051, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': "No assistant found with id 'asst_sJetDGPplUfiq0x03Ba8Xvzq'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-09-28 10:42:57 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000018F29E328D0>
2024-09-28 10:44:27 - __main__ - ERROR - Error in webhook handler: Error code: 404 - {'error': {'message': "No assistant found with id 'asst_sJetDGPplUfiq0x03Ba8Xvzq'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    response = get_ai_text(message.text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 21, in get_ai_text
    run = client.beta.threads.runs.create_and_poll(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\runs\runs.py", line 788, in create_and_poll
    run = self.create(
          ^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\runs\runs.py", line 535, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 947, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1051, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': "No assistant found with id 'asst_sJetDGPplUfiq0x03Ba8Xvzq'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-09-28 10:45:27 - __main__ - ERROR - Error in webhook handler: Error code: 404 - {'error': {'message': "No assistant found with id 'asst_sJetDGPplUfiq0x03Ba8Xvzq'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    response = get_ai_text(message.text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 21, in get_ai_text
    run = client.beta.threads.runs.create_and_poll(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\runs\runs.py", line 788, in create_and_poll
    run = self.create(
          ^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\runs\runs.py", line 535, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 947, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1051, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': "No assistant found with id 'asst_sJetDGPplUfiq0x03Ba8Xvzq'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-09-28 10:49:18 - __main__ - ERROR - Error in webhook handler: Error code: 404 - {'error': {'message': "No assistant found with id 'asst_sJetDGPplUfiq0x03Ba8Xvzq'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 47, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    response = get_ai_text(message.text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\get_price_with_ai.py", line 21, in get_ai_text
    run = client.beta.threads.runs.create_and_poll(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\runs\runs.py", line 788, in create_and_poll
    run = self.create(
          ^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\resources\beta\threads\runs\runs.py", line 535, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 947, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\openai\_base_client.py", line 1051, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': "No assistant found with id 'asst_sJetDGPplUfiq0x03Ba8Xvzq'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-09-28 10:50:47 - __main__ - INFO - Status: ok
2024-09-28 10:51:07 - __main__ - INFO - Status: ok
2024-09-28 10:52:05 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002145B9F9F90>
2024-09-28 10:52:33 - __main__ - INFO - Status: ok
2024-09-28 10:52:57 - __main__ - INFO - Status: ok
2024-09-28 10:54:50 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000253B9FF6CD0>
2024-09-28 10:55:20 - __main__ - INFO - Status: ok
2024-09-28 10:55:31 - __main__ - INFO - Status: ok
2024-09-28 10:56:01 - __main__ - INFO - Status: ok
2024-09-28 10:56:16 - __main__ - INFO - Status: ok
2024-09-28 10:56:31 - __main__ - INFO - Status: ok
2024-09-28 10:56:56 - __main__ - INFO - Status: ok
2024-09-28 10:57:12 - __main__ - INFO - Status: ok
2024-09-28 10:59:30 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001FC50177F90>
2024-09-28 15:56:37 - __main__ - INFO - Status: ok
2024-09-28 16:01:05 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F9B1424CD0>
2024-09-28 16:02:35 - __main__ - INFO - Status: ok
2024-09-28 16:03:13 - __main__ - INFO - Status: ok
2024-09-28 16:08:44 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020D10EF1D50>
2024-09-28 16:09:49 - __main__ - INFO - Status: ok
2024-09-28 16:10:05 - __main__ - INFO - Status: ok
2024-09-28 16:10:34 - __main__ - INFO - Status: ok
2024-09-28 16:24:26 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021A606B1E10>
2024-09-28 16:25:10 - __main__ - INFO - Status: ok
2024-09-28 16:26:31 - __main__ - INFO - Status: ok
2024-09-28 16:37:18 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001E259A8DB50>
2024-09-28 16:38:13 - __main__ - ERROR - Error in webhook handler: 'questions'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 37, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 15, in callback_handler
    questions = quizz(response) # создали вопрос
                ^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\quizz.py", line 35, in quizz
    questions = data['questions']
                ~~~~^^^^^^^^^^^^^
KeyError: 'questions'
2024-09-28 16:38:53 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000029AD21377D0>
2024-09-28 16:40:08 - __main__ - ERROR - Error in webhook handler: 'questions'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 37, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 15, in callback_handler
    questions = quizz(response) # создали вопрос
                ^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\quizz.py", line 35, in quizz
    questions = data['questions']
                ~~~~^^^^^^^^^^^^^
KeyError: 'questions'
2024-09-28 16:40:53 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001EADB7377D0>
2024-09-28 16:41:29 - __main__ - ERROR - Error in webhook handler: 'questions'
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 37, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 15, in callback_handler
    questions = quizz(response) # создали вопрос
                ^^^^^^^^^^^^^^^
  File "c:\Users\user\1\hackaton\utils\quizz.py", line 35, in quizz
    questions = data['questions']
                ~~~~^^^^^^^^^^^^^
KeyError: 'questions'
2024-09-28 16:42:15 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002DFECDB7C10>
2024-09-28 16:42:54 - __main__ - ERROR - Error in webhook handler: 2 validation errors for SendPoll
question
  Input should be a valid string [type=string_type, input_value=['400+', '3000+', '150'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
options
  Input should be a valid list [type=list_type, input_value='Сколько акти...ает Латокен?', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/list_type
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 37, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    await bot.send_poll(chat_id=message.chat.id, question=questions, options=answers, is_anonymous=False)
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\aiogram\client\bot.py", line 2938, in send_poll
    call = SendPoll(
           ^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for SendPoll
question
  Input should be a valid string [type=string_type, input_value=['400+', '3000+', '150'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
options
  Input should be a valid list [type=list_type, input_value='Сколько акти...ает Латокен?', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/list_type
2024-09-28 16:45:27 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000019067F37950>
2024-09-28 16:46:12 - __main__ - ERROR - Error in webhook handler: 2 validation errors for SendPoll
question
  Input should be a valid string [type=string_type, input_value=['Глобальная п...ля торговли'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
options
  Input should be a valid list [type=list_type, input_value='Почему Latoken в...их платформ?', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/list_type
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 37, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 18, in callback_handler
    await bot.send_poll(chat_id=message.chat.id, question=questions, options=answers, is_anonymous=False)
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\aiogram\client\bot.py", line 2938, in send_poll
    call = SendPoll(
           ^^^^^^^^^
  File "C:\Users\user\1\tg_bots\tgbotenv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for SendPoll
question
  Input should be a valid string [type=string_type, input_value=['Глобальная п...ля торговли'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
options
  Input should be a valid list [type=list_type, input_value='Почему Latoken в...их платформ?', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/list_type
2024-09-28 16:47:51 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000176A9DFCE50>
2024-09-28 16:48:42 - __main__ - ERROR - Error in webhook handler: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 37, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    data = json.loads(questions)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
2024-09-28 16:49:05 - __main__ - ERROR - Error in webhook handler: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "c:\Users\user\1\hackaton\webhook.py", line 37, in webhook_handler
    await callback_handler(update.message)
  File "c:\Users\user\1\hackaton\handlers\callback_handlers.py", line 16, in callback_handler
    data = json.loads(questions)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
2024-09-28 16:50:52 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020589837510>
2024-09-28 16:51:32 - __main__ - INFO - Status: ok
2024-09-28 16:54:33 - __main__ - INFO - Status: ok
2024-09-28 16:57:50 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002BAA8C2BE50>
2024-09-28 16:59:19 - __main__ - INFO - Status: ok
2024-09-28 16:59:49 - __main__ - INFO - Status: ok
2024-09-28 17:00:09 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002BB65BB2090>
2024-09-28 18:51:53 - __main__ - INFO - Status: ok
2024-09-28 18:52:14 - __main__ - INFO - Status: ok
2024-09-28 18:52:35 - __main__ - INFO - Status: ok
2024-09-28 18:52:54 - __main__ - INFO - Status: ok
2024-09-28 18:53:13 - __main__ - INFO - Status: ok
2024-09-28 18:53:36 - __main__ - INFO - Status: ok
2024-09-28 18:53:56 - __main__ - INFO - Status: ok
2024-09-28 18:59:38 - __main__ - INFO - Status: ok
2024-09-28 19:00:28 - __main__ - INFO - Status: ok
2024-09-28 19:01:46 - __main__ - INFO - Status: ok
2024-09-28 19:02:20 - __main__ - INFO - Status: ok
2024-09-28 19:03:03 - __main__ - INFO - Status: ok
2024-09-28 19:03:54 - __main__ - INFO - Status: ok
2024-09-28 19:04:28 - __main__ - INFO - Status: ok
2024-09-28 19:04:28 - __main__ - INFO - Status: ok
2024-09-28 19:08:26 - __main__ - INFO - Status: ok
2024-09-28 19:08:56 - __main__ - INFO - Status: ok
2024-09-28 19:09:55 - __main__ - INFO - Status: ok
2024-09-28 19:18:33 - __main__ - INFO - Status: ok
2024-10-22 12:50:03 - __main__ - ERROR - Error in webhook handler: 'int' object is not iterable
Traceback (most recent call last):
  File "c:\Users\user\1\tg_bots\test_llm_bot\webhook.py", line 37, in webhook_handler
    await message_hendler(update.message)
  File "c:\Users\user\1\tg_bots\test_llm_bot\handlers\callback_handlers.py", line 9, in message_hendler
    response = get_ai_text(user_nickname, message.text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\tg_bots\test_llm_bot\utils\get_conversation_with_ai.py", line 26, in get_ai_text
    for id in user_nickname:
TypeError: 'int' object is not iterable
2024-10-22 12:50:09 - __main__ - ERROR - Error in webhook handler: 'int' object is not iterable
Traceback (most recent call last):
  File "c:\Users\user\1\tg_bots\test_llm_bot\webhook.py", line 37, in webhook_handler
    await message_hendler(update.message)
  File "c:\Users\user\1\tg_bots\test_llm_bot\handlers\callback_handlers.py", line 9, in message_hendler
    response = get_ai_text(user_nickname, message.text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\1\tg_bots\test_llm_bot\utils\get_conversation_with_ai.py", line 26, in get_ai_text
    for id in user_nickname:
TypeError: 'int' object is not iterable
2024-10-22 12:58:21 - __main__ - INFO - Status: ok
2024-10-22 12:58:27 - __main__ - INFO - Status: ok
2024-10-22 12:58:44 - __main__ - INFO - Status: ok
2024-10-22 12:59:25 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002ACD1154C90>
2024-10-22 12:59:55 - __main__ - INFO - Status: ok
2024-10-22 13:00:35 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000026F3FB33650>
2024-10-22 13:01:01 - __main__ - INFO - Status: ok
2024-10-22 13:01:30 - __main__ - INFO - Status: ok
2024-10-22 13:02:26 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000134DAEF8ED0>
2024-10-22 13:03:01 - __main__ - INFO - Status: ok
2024-10-22 13:03:51 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002E9A622B950>
2024-10-22 13:08:47 - __main__ - INFO - Status: ok
2024-10-22 13:08:54 - __main__ - INFO - Status: ok
2024-10-22 13:09:02 - __main__ - INFO - Status: ok
2024-10-22 13:09:50 - __main__ - INFO - Status: ok
2024-10-22 13:10:45 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001EB383A0D90>
2024-10-22 13:26:37 - __main__ - INFO - Status: ok
2024-10-22 13:32:06 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000010B3DED13D0>
